### ISSUE TITLE
setCurrentIndex bug

### ISSUE THREAD

**Issue by LuciusVorenus98** [MATF-Computer-Networks-Projects/2020_Domino-Kingdoms#1]
Da li mozete da proverite zasto setCurrentIndex metod u mainwindow.cpp fajlu u 37. liniji ne radi kada mu se kao argument prosledi promenljiva tipa int a radi kada se prosledi konkretan int? Zbog ovoga ne radi back dugme ni na jednom prozoru, a vrednosti backIndex promenljive su dobre.

**Comment by ivan-ristovic** [comment]
Imate samo problem u logici, pogledajte liniju: https://github.com/MATF-Computer-Networks-Projects/2020_Domino-Kingdoms/blob/3513abfb0ae12bb8cc45311889e6c7f839d54d81/DominoKingdoms/mainwindow.cpp#L37

Ovde se `currentIndex` menja na `backIndex` koji je, ako smo trenutno bili na indeksu `3` npr, ostao i dalje `3`. Ako promenimo kod tako da `setCurrentIndex()` funkciji prosledi vrednost `backIndex - 1`, verovatno cete dobiti ocekivano ponasanje. Morate naravno dodati par provera ali mislim da je to sustina problema. 

U nastavku je par saveta:

Promenljiva `backIndex` nije deklarisana u okviru klase `MainWindow`, moze biti privatna clanica (greske poput ove mozete vrlo lako uociti dodavanjem `clang` plugina u QtCreator).

Dodajte `.gitignore` za C++/Qt, kako ne biste pushovali i build fajlove na GitHub. Preporucujem [automatsko generisanje .gitignore fajla](https://www.toptal.com/developers/gitignore).

Ako radite debug logging i koristite `printf`, nece se ispisati izlaz dok ne stopirate program (zbog baferisanja). Posto radite u C++-u, koristite `std::cerr` output stream, dakle: 
```cpp
std::cerr << "debug value: " << value << std::endl;
```
Alternativno, preporucujem i debug sistem Qt radnog okvira:
```cpp
#include <QDebug>

// ...

qDebug() << "debug value: " << value;          // auto newline
```
Tako dobijate ispis onog trenutka kada se pozove kod za debug ispis.

**Comment by marakuja98** [comment]
Hvala vam!

**Comment by LuciusVorenus98** [comment]
Hvala puno
